employee_details/config/routes.rb
Rails.application.routes.draw do

get "employee/new" => 'employees#new', :as => 'employee_new'
post "employee/new" => 'employees#create', :as => 'employee_create'

get "employee/list" => 'employees#index', :as => 'employees_list'

get "employee/:id/edit" => 'employees#edit', :as => 'employee_edit'
put "employee/:id/edit" => 'employees#update', :as => 'employee_update'

delete "employee/:id" => 'employees#destroy', :as => 'employee_destroy'

end

employee_details/app/models/employee.rb
class Employee < ActiveRecord::Base
	 
end

employee_details/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def new
		@employee=Employee.new
	end

	def index
		@employees=Employee.all
	end

	def create
		binding.pry
		@employee=Employee.new(employee_params)
		@employee.save
		redirect_to employees_list_path
	end

	def edit
		@employee=Employee.find_by_id(params[:id])
	end

	def update
		@employee=Employee.find_by_id(params[:id])
		@employee.update_attributes(employee_params)
		redirect_to employees_list_path
	end

	def destroy
		@employee=Employee.find_by_id(params[:id])
		@employee.destroy
		redirect_to employees_list_path
	end

	private
	def employee_params
		params.require(:employee).permit(:first_name,:last_name,:email,:password)
	end
end

employee_details/app/helpers/employees_helper.rb
module EmployeesHelper
end

employee_details/app/views/employees/edit.html.erb
<h2>Edit Employees</h2>
<%= form_for :employee, url: employee_edit_path(@employee), method: :put do |f| %>

<p>
<%= f.label :first_name %><br>
<%= f.text_field :first_name %>
</p>

<p>
<%= f.label :last_name %><br>
<%= f.text_field :last_name %>
</p>

<p>
<%= f.label :email %><br>
<%= f.text_field :email %>
</p>

<p>
<%= f.label :password %><br>
<%= f.password_field :password %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

employee_details/app/views/employees/index.html.erb
<h2>Employees details</h2>
<table border="2px">
	<tr>
		<th>First_name</th>
		<th>Last_name</th>
		<th>Email</th>
	</tr>

<% @employees.each do |employee| %><br>
	<tr>
		<td><%= employee.first_name %></td>
		<td><%= employee.last_name %></td>
		<td><%= employee.email %></td>
		<td><%= link_to 'Edit User', employee_edit_path(employee) %></td>
		<td><%= link_to 'Destroy User', employee_destroy_path(employee), method: :delete, data: {confirm: 'Are you sure?'} %></td>
	</tr>
<% end %>
</table>

employee_details/app/views/employees/new.html.erb
<%= form_for :employee do |f| %>
<p>
<%= f.label :first_name %><br>
<%= f.text_field :first_name %>
</p>

<p>
<%= f.label :last_name %><br>
<%= f.text_field :last_name %>
</p>

<p>
<%= f.label :email %><br>
<%= f.text_field :email %>
</p>

<p>
<%= f.label :password %><br>
<%= f.password_field :password %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

employee_details/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeDetails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>