user_details/config/routes.rb
Rails.application.routes.draw do

get "/user/profile" => 'users#profile', :as => 'user_profile'

get "user/new" => 'users#new', :as => 'user_new'
post "user/new" => 'users#create', :as => 'user_create'

get "user/list" => 'users#index', :as => 'users_list'

get "user/:id/edit" => 'users#edit', :as => 'user_edit'
put "user/:id/edit" => 'users#update', :as => 'user_update'

delete "user/:id" => 'users#destroy', :as => 'user_destroy'

end

user_details/app/models/project.rb
class Project < ActiveRecord::Base
end

user_details/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	

	validates :first_name,:last_name,presence: true
	validates :email,presence: true,uniqueness: true
	
validates :password, :presence => true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{8,})\z/, message: "Not valid" }
end

user_details/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

user_details/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

user_details/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end

	def index
		@users=User.all
	end

	def profile
		@user=User.all
	end

	def create
		@user=User.new(user_params)
		if @user.save
		redirect_to users_list_path
	else
		render 'new'
	end

	end

	def edit
		@user=User.find_by_id(params[:id])
	end

	def update
		@user=User.find_by_id(params[:id])
		@user.update_attributes(user_params)
		redirect_to users_list_path
	end

	def destroy
		@user=User.find_by_id(params[:id])
		@user.destroy
		redirect_to users_list_path
	end

	private
	def user_params
		params.require(:user).permit(:first_name,:last_name,:email,:password)
	end
end

user_details/app/helpers/application_helper.rb
module ApplicationHelper
end

user_details/app/helpers/projects_helper.rb
module ProjectsHelper
end

user_details/app/helpers/users_helper.rb
module UsersHelper
end

user_details/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserDetails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

user_details/app/views/users/edit.html.erb
<h2>Edit Employees</h2>
<%= form_for :user, url: user_edit_path(@user), method: :put do |f| %>

<p>
<%= f.label :first_name %><br>
<%= f.text_field :first_name %>
</p>

<p>
<%= f.label :last_name %><br>
<%= f.text_field :last_name %>
</p>

<p>
<%= f.label :email %><br>
<%= f.text_field :email %>
</p>



<p>
<%= f.submit %>
</p>
<% end %>

user_details/app/views/users/index.html.erb
<h2>Users details</h2>
<table border="2px">
	<tr>
		<th>First_name</th>
		<th>Last_name</th>
		<th>Email</th>
	</tr>

<% @users.each do |user| %><br>
	<tr>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'Edit User', user_edit_path(user) %></td>
		<td><%= link_to 'Destroy User', user_destroy_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		
	</tr>
<% end %>
</table>

user_details/app/views/users/new.html.erb
<%= form_for :user do |f| %>
<% @user.errors.each do |attr, msg| %>
<%= "#{attr} #{msg}" if @user.errors[attr].first == msg %>
<% end %>
<p>
<%= f.label :first_name %><br>
<%= f.text_field :first_name %>
</p>

<p>
<%= f.label :last_name %><br>
<%= f.text_field :last_name %>
</p>

<p>
<%= f.label :email %><br>
<%= f.text_field :email %>
</p>

<p>
<%= f.label :password %><br>
<%= f.password_field :password %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

user_details/app/views/users/profile.html.erb
<h2>Profile details</h2>
<table border="2px">
	<tr>
		<th>First_name</th>
		<th>Last_name</th>
		<th>Email</th>
	</tr>

<% @user.each do |user| %><br>
	<tr>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'Edit and update', user_edit_path(user) %></td>
	</tr>
		
<% end %>
</table>